# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GDG DevFest Season 2014"
email: "gdgkyoto@kyoto-gtug.org"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "http://gdgkyoto.github.io"
#permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdgkyoto.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Kyoto"
organizerAlternateName: "Google Developer Group Kyoto"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgkyoto@kyoto-gtug.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://sites.google.com/a/kyoto-gtug.org/home/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, polymer, go, gas, developers, Kyoto"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "http://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "http://goo.gl/gs1X7j", text: "Resistration"}
rightNavigationButtons:
 - {link: "http://goo.gl/gs1X7j", text: "Resistration"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest Kyoto 2014 <typeout>"
eventDate: "September - November, 2014"
typeoutTextValues: '"", "Polymer", "Go", "GAS", "Other"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://goo.gl/gs1X7j", text: "Reagistration"}

# About Block
aboutTitle: "About GDG DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "60", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "6", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "6", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "1", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
# latestNewsTitle: "Latest news"

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
#rockstarSpeakersCount: 6
#rockstarSpeakersTitle: "Rockstar speakers"
#rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Kyoto Reseach Park"
eventLocationLink: "http://www.krp.co.jp/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Kyoto"
eventAddressLocalityRegion: "Kyoto"
eventPostalCode: ""
eventAddressCountry: "Japan"
eventStartTime: "2014-11-22T13:00"
eventDoorTime: "12:30"
eventEndTime: "2014-11-22T21:00"
eventPlaceCoordinates: "34.995063, 135.739614"
mapCenterCoordinates: "34.995063, 135.739614"
mapMobileCenterCoordinates: "34.995063, 135.739614"


# Venue Block
 venueBlockTitle: "Venue"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"


# Partners Block
organizersTitle: "Organizers"
#partnersTitle: "Partners"
#partnersC4sponsorsButton: "Become a sponsor"
